logger:
    level: DEBUG
console:
  max_message_size_bytes: 409600
runtime:
  js_entrypoint: "build/index.js"
  env:
    - "blockchain_auth_service_url=https://blockchain-auth-service.starci.net/api"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072