logger:
    level: DEBUG
console:
  max_message_size_bytes: 409600
runtime:
  js_entrypoint: "build/index.js"
  env:
    # - "cifarm-periphery-api-url=https://api.cifarm.starci.net/api/v1"
    # - "cifarm-periphery-graphql-url=https://api.cifarm.starci.net/graphql"
    - "cifarm-periphery-api-url=http://192.168.1.10:9999/api/v1"
    - "cifarm-periphery-graphql-url=http://192.168.1.10:9999/graphql"
    - "cifarm-periphery-websocket-url=ws://192.168.1.10:9999"
session:
  encryption_key: "948033f7-f3b3-4311-9017-d7557d5b65c6"
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072