logger:
    level: DEBUG
console:
  max_message_size_bytes: 409600
runtime:
  js_entrypoint: "build/index.js"
  env:
    # - "cifarm-periphery-api-url=https://api.cifarm.starci.net/api/v1"
    # - "cifarm-periphery-graphql-url=https://api.cifarm.starci.net/graphql"
    - "cifarm-periphery-api-url=http://10.216.1.94:9999/api/v1"
    - "cifarm-periphery-graphql-url=http://10.216.1.94:9999/graphql"
    - "cifarm-periphery-websocket-url=ws://10.216.1.94:9999"
    - "minter-private-key=8a27d62c2184c6503c84065f6abe837cc2173bb9e5ddca5d52d9c7c46db6cdbb"
    - "utility-token-address=0xA9E72Ae9FfEc2a10AA9b6d617d1faf4953A2dADD"
session:
  encryption_key: "948033f7-f3b3-4311-9017-d7557d5b65c6"
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072