logger:
    level: DEBUG
console:
  max_message_size_bytes: 409600
runtime:
  js_entrypoint: "build/index.js"
  env:
    - "ci_base_api_url=https://blockchain-auth-service.starci.net/api/v1"
    - "ci_base_graphql_url=https://blockchain-auth-service.starci.net/graphql"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072